export const GET_PETS = "GET_PETS";
export const FETCH_PET_DETAIL_SUCCESS = 'FETCH_PET_DETAIL_SUCCESS';
export const GET_PETS_RAMDON_HOME = "GET_PETS_RAMDON_HOME";
export const GET_PET_BY_NAME = "GET_PET_BY_NAME";
// export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM'


export const REGISTER_USER = 'REGISTER_USER';



